baseurl = "/"
canonifyURLs = true
disqusShortname = "shortname"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-uk"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Adrian Zucco - Bioinformatics and AI"
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[params]
categoriesbycount = true
customcss = ["default"]
customjs = ["default"]
description = "Personal website"
disable_highlight = false
dynamictitles = true
faviconversion = ""
highlightjscdn = "//cdn.bootcss.com"
highlightjslang = ["r", "yaml", "css"]
highlightjstheme = "github"
highlightjsversion = "9.11.0"
includereadingtime = true
loadfavicon = false
mathjaxcdn = "//cdn.bootcss.com"
mathjaxversion = "2.7.1"
navbartitle = "Adrian Zucco"
rssappearatbottom = true
rssappearattop = true
showsidebarcategories = true
socialappearatbottom = true
socialappearattop = true
socialshare = true
socialshareemail = true
socialsharefacebook = true
socialsharegoogleplus = true
socialsharelinkedin = true
socialsharepinterest = true
socialsharereddit = true
socialsharestumbleupon = true
socialsharetwitter = true
viewmorepostlink = "/blog/"
[params.intro]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
header = "Adrian Zucco"
paragraph = "Bioinformatics and Machine Learning"
[params.intro.pic]
alt = "AGZ"
circle = false
imperfect = true
src = "/img/main/me.jpg"
width = ""
[params.postamount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
github = "adrigabzu"
gitlab = ""
googlescholar = "fwnY4t0AAAAJ"
linkedin = "adrian-gabriel-zucco-82184a72"
researchgate = "Adrian_Gabriel_Zucco"
skype = "adrianzucco"
twitter = "adrigabzu"
